services:

  nestar-api:
    container_name: job-board-ai
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 4001:3005
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - MONGO_PROD=${MONGO_PROD}
      - MONGO_DEV=${MONGO_DEV}
    env_file:
      - .env
    networks:
      - monorepo-network

  nestar-batch:
    container_name: nestar-batch
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.batch
    ports:
      - 4002:3006
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - MONGO_PROD=${MONGO_PROD}
      - MONGO_DEV=${MONGO_DEV}
    env_file:
      - .env
    networks:
      - monorepo-network

networks:
  monorepo-network:
    driver: bridge